"""Add Corporate model

Revision ID: 2fc705009228
Revises: 6e3a6999f5c1
Create Date: 2025-07-04 23:02:59.959268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fc705009228'
down_revision: Union[str, None] = '6e3a6999f5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aggregated_news_slug', table_name='aggregated_news')
    op.drop_table('aggregated_news')
    op.drop_table('original_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('original_content',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subcategory_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', name='original_content_status'), autoincrement=False, nullable=True),
    sa.Column('written_by_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('edited_by_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_by_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name='original_content_approved_by_id_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='original_content_category_id_fkey'),
    sa.ForeignKeyConstraint(['edited_by_id'], ['users.id'], name='original_content_edited_by_id_fkey'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name='original_content_subcategory_id_fkey'),
    sa.ForeignKeyConstraint(['written_by_id'], ['users.id'], name='original_content_written_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='original_content_pkey')
    )
    op.create_table('aggregated_news',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'published', name='agg_news_status'), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('meta_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('shares', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subcategory_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('written_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('edited_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='aggregated_news_approved_by_fkey'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='aggregated_news_category_id_fkey'),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name='aggregated_news_edited_by_fkey'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name='aggregated_news_subcategory_id_fkey'),
    sa.ForeignKeyConstraint(['written_by'], ['users.id'], name='aggregated_news_written_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='aggregated_news_pkey')
    )
    op.create_index('ix_aggregated_news_slug', 'aggregated_news', ['slug'], unique=True)
    # ### end Alembic commands ###
