"""Change article.author to string name

Revision ID: 3223f175132b
Revises: 2fc705009228
Create Date: 2025-07-06 12:47:20.099644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3223f175132b'
down_revision: Union[str, None] = '2fc705009228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('articles_author_fkey', 'articles', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('articles_author_fkey', 'articles', 'users', ['author'], ['id'])
    op.alter_column('articles', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
