"""Update User and Article relationships

Revision ID: 32de9163784a
Revises: ee5b8c29e6c9
Create Date: 2025-07-06 14:08:05.034487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32de9163784a'
down_revision: Union[str, None] = 'ee5b8c29e6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'written_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'written_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
