"""Add new tables for articles, profiles, resources, etc.

Revision ID: 34334047927e
Revises: 43ccca15d49c
Create Date: 2025-06-01 12:51:21.126262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34334047927e'
down_revision: Union[str, None] = '43ccca15d49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
