"""add_requires_password_reset

Revision ID: 43ccca15d49c
Revises: cb111da7a44f
Create Date: 2025-05-29 02:15:02.379087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ccca15d49c'
down_revision: Union[str, None] = 'cb111da7a44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('requires_password_reset', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'requires_password_reset')
    # ### end Alembic commands ###
