"""Add category/subcategory to OriginalContent

Revision ID: 5b38111b27f1
Revises: 232c1f38695f
Create Date: 2025-05-14 06:48:03.095428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b38111b27f1'
down_revision: Union[str, None] = '232c1f38695f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('original_content', sa.Column('category_id', sa.String(), nullable=True))
    op.add_column('original_content', sa.Column('subcategory_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'original_content', 'subcategories', ['subcategory_id'], ['id'])
    op.create_foreign_key(None, 'original_content', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'original_content', type_='foreignkey')
    op.drop_constraint(None, 'original_content', type_='foreignkey')
    op.drop_column('original_content', 'subcategory_id')
    op.drop_column('original_content', 'category_id')
    # ### end Alembic commands ###
