"""create resources tables

Revision ID: 807cfbabeec9
Revises: 8329a84f8390
Create Date: 2025-08-07 21:54:30.237689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '807cfbabeec9'
down_revision: Union[str, None] = '8329a84f8390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('updated', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=False),
    sa.Column('button_link', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=False),
    sa.Column('button_link', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('published', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=False),
    sa.Column('button_link', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('subcategories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('featured_insight_id', sa.String(), nullable=False),
    sa.Column('report_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('data_insight_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('event_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['featured_insight_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_data_insights',
    sa.Column('resources_id', sa.String(), nullable=True),
    sa.Column('data_insight_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_insight_id'], ['data_insights.id'], ),
    sa.ForeignKeyConstraint(['resources_id'], ['resources.id'], )
    )
    op.create_table('resource_events',
    sa.Column('resources_id', sa.String(), nullable=True),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['resources_id'], ['resources.id'], )
    )
    op.create_table('resource_reports',
    sa.Column('resources_id', sa.String(), nullable=True),
    sa.Column('report_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['resources_id'], ['resources.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_reports')
    op.drop_table('resource_events')
    op.drop_table('resource_data_insights')
    op.drop_table('resources')
    op.drop_table('subcategories')
    op.drop_table('reports')
    op.drop_table('events')
    op.drop_table('data_insights')
    op.drop_table('categories')
    # ### end Alembic commands ###
