"""Change author from FK to string

Revision ID: 81ec699e429e
Revises: 41fe3c0eb630
Create Date: 2025-07-06 12:59:48.420879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ec699e429e'
down_revision: Union[str, None] = '41fe3c0eb630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'articles', 'users', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.alter_column('articles', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
