"""Add SUPERADMIN to Role enum

Revision ID: a7e068bab5c8
Revises: 5b38111b27f1
Create Date: 2025-05-14 15:22:20.735498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e068bab5c8'
down_revision: Union[str, None] = '5b38111b27f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
