"""add_resource_models

Revision ID: bac0de870ae9
Revises: 4f4dfa6d69e7
Create Date: 2025-06-08 23:30:46.609315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac0de870ae9'
down_revision: Union[str, None] = '4f4dfa6d69e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
