"""Add SUPERADMIN to Role enum

Revision ID: ed848d0d8f92
Revises: 3d2d6a90c2ce
Create Date: 2025-05-14 15:38:34.860542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed848d0d8f92'
down_revision: Union[str, None] = '3d2d6a90c2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
